### ISSUE TITLE
Some Suggestions

### ISSUE THREAD

**Issue by tmountain** [artdarek/go-unzip#4]
Hi, thanks for the library. Dropping in to make a few quick suggestions:

1) Your Extract() function is set up to print status messages no matter what:

       fmt.Println("Extraction of " + uz.Src + " started!")

This is considered a side-effect (i.e., I'm asking to extract not to print status), and there is no way to turn it off. There are definitely use cases where a user would not want to print status upon extraction, so you should add a "verbose" option or something similar to give your users agency regarding whether they want to see these messages.

2) The Extract() function does not provide a way to retrieve a list of the files extracted. This one is pretty crucial because a user may need to do secondary post-processing on the extracted files, and currently, there's no way to iterate over them.

A simple fix would be to modify the return value of Extract to something more flexible:

     (uz Unzip) Extract(verbose bool) ([]*zip.File, error) 
     or maybe just...
     (uz Unzip) Extract(verbose bool) ([]string, error)

These are issues I have run into in using the library, so I hope this is helpful.

**Comment by artdarek** [comment]
Thanks for all your suggestions, I did a small refactor today based on those 👍
